language: node_js
dist: trusty
git:
  depth: false

node_js:
  - '12'

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: 'Test'
      script:
        - yarn test
        - ${TRAVIS_BUILD_DIR}/node_modules/.bin/codecov
    - stage: 'Build and Deploy'
      before_script:
        - git checkout ${TRAVIS_BRANCH}
      script: yarn build
      before_deploy:
        - bash ./scripts/ci/setup-npm.sh
      deploy:
        - provider: script
          script: bash ./scripts/ci/release-snapshot.sh
          skip_cleanup: true
          on:
            branch: master
