name: 'Release - Snapshot'

on:
  workflow_dispatch

jobs:
  build-and-release:
    if: github.actor == 'MarcusNotheis' || github.actor == 'vbersch' || github.actor == 'Lukas742'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      - name: Install, test and build
        run: |
          yarn install
          yarn build

      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}

          git config user.email ${{ secrets.BOT_GIT_EMAIL }}
          git config user.name ${{ secrets.BOT_GIT_USERNAME }}

          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          ${GITHUB_WORKSPACE}/node_modules/.bin/lerna publish "0.0.0-${git_hash}" \
            --exact \
            --no-push \
            --no-git-tag-version \
            --dist-tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
